import pytest

from gobugminer.metrics.go import classify, go_counts


def test_go_classification() -> None:
    assert classify("main.go", "package main") == (True, "production_go")
    assert classify("main_test.go", "package main") == (False, "test_go")
    assert classify("vendor/x.go", "package x") == (False, "vendor")
    assert classify("x.py", "") == (False, "non_go")
    generated = "// Code generated by fixture. DO NOT EDIT.\npackage x\n"
    assert classify("x.go", generated) == (False, "generated_go")


def test_go_ast_counts() -> None:
    counts = go_counts(
        """package p
type S struct{}
type I interface{ M() }
func f() {
  defer g()
  go g()
  for i := 0; i < 1; i++ {}
  if err != nil {}
  _ = make(chan int)
}
"""
    )
    assert counts["struct_count"] == 1
    assert counts["interface_count"] == 1
    assert counts["defer_count"] == 1
    assert counts["goroutine_count"] == 1
    assert counts["loop_count"] == 1
    assert counts["error_handling_count"] == 1
    assert counts["channel_count"] >= 1


@pytest.mark.parametrize(
    ("construct", "metric"),
    [
        ("func f() { if err != nil {} }", "error_handling_count"),
        ("func f(ctx context.Context) {}", "context_usage_count"),
        ("func f(values ...int) {}", "variadic_function_count"),
        ("func (s *Service) f() {}", "pointer_receiver_count"),
        ('type S struct { Name string `json:"name"` }', "json_tag_count"),
    ],
)
def test_unicode_before_construct_does_not_change_counts(construct: str, metric: str) -> None:
    ascii_source = f'package p\nvar _ = "ascii"\n{construct}\n'
    unicode_source = f'package p\nvar _ = "Türkçe 日本語"\n{construct}\n'
    assert go_counts(unicode_source)[metric] == go_counts(ascii_source)[metric] == 1


@pytest.mark.parametrize(
    ("declaration", "expected"),
    [
        ("func f() {}", {}),
        ("func (s Service) f() {}", {}),
        ("func (s *Service) f() {}", {"pointer_receiver_count": 1}),
        ("func f(values ...int) {}", {"variadic_function_count": 1}),
        ("func f() { for range []int{} {} }", {"loop_count": 1}),
        ("func f() { defer g() }", {"defer_count": 1}),
        ("func f() { go g() }", {"goroutine_count": 1}),
        ("func f(ch chan int) { ch <- 1 }", {"channel_count": 1}),
        ("func f() { if err != nil {} }", {"error_handling_count": 1}),
        ("// Türkçe 日本語\nfunc f() { if err != nil {} }", {"error_handling_count": 1}),
    ],
)
def test_wrapped_method_declarations_parse_reliably(
    declaration: str,
    expected: dict[str, int],
) -> None:
    counts = go_counts(declaration, wrap_declaration=True)
    assert counts["parse_failure"] is False
    for metric, value in expected.items():
        assert counts[metric] == value


def test_wrapped_malformed_declaration_reports_parse_failure() -> None:
    assert go_counts("func f(", wrap_declaration=True)["parse_failure"] is True
